name: Download Artifact
on:
  workflow_dispatch:
jobs:
  d-art:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/eSandrone/testCustomActions/actions/artifacts/464514801/zip
            -D
