# This is a basic workflow to help you get started with Actions

name: jobCalledWithMatrix

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      ID_RUN:
        type: string
      IMAGE:
        type: string
    outputs:
      urls2:
        description: "test url"
        value: ${{ jobs.read_env_file.outputs.url-list }}
env:
  URLS: "AAA,"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    outputs:
      url-list: ${{ steps.url-getter.outputs.url }}
    strategy:
      matrix: ${{ fromJson(inputs.IMAGE) }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      
      - name: usrl
        id: url-getter
        run: |
          URLS2="${{ matrix.app }},"
          echo $URLS2
          #echo "url=$URLS2" >> $GITHUB_OUTPUT
          curl -H "Authorization: token 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" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          "https://api.github.com/repos/eSandrone/testCustomActions/dispatches" \
          -d '{"event_type": "awesomeness", "client_payload": {"url": "$URLS2", "run_id": "${{ inputs.RUN_ID }}"}}'
          echo "::set-output name=url::$URLS2"
          
  print-env-var:
    needs: read_env_file
    runs-on: ubuntu-latest
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      
      - run: |
          echo $URLS
          
