# This is a basic workflow to help you get started with Actions

name: jobCalledWithMatrix

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      NAME:
        type: string
      DATE:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.set-env.outputs.app_updated }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      
      - run: |
          echo ${{ inputs.NAME }}
          echo ${{ inputs.DATE }}
