# This is a basic workflow to help you get started with Actions

name: jobCalledWithMatrix

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      ID_RUN:
        type: string
      IMAGE:
        type: string
    outputs:
      URLS2: 
        value: ${{ jobs.read_env_file.outputs.urls }}
env:
  URLS: "AAA,"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    outputs:
      url-list: ${{ steps.url-getter.outputs.urls }}
    strategy:
      matrix: ${{ fromJson(inputs.IMAGE) }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      
      - name: usrl
        id: url-getter
        run: |
          echo ${{ inputs.ID_RUN }}
          echo ${{ matrix.app }}
          echo ${{ env.URLS }}
          URLS="$${{ matrix.app }},"
          echo ${{env.URLS}}
          echo "urls=$URLS" >> $GITHUB_OUTPUT
          
  print-env-var:
    needs: read_env_file
    runs-on: ubuntu-latest
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      
      - run: |
          echo $URLS
          
