# This is a basic workflow to help you get started with Actions

name: jobCalledWithMatrix

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      ID_RUN:
        type: string
      IMAGE:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(inputs.IMAGE) }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      
      - run: |
          echo ${{ inputs.ID_RUN }}
          echo ${{ inputs.IMAGE }}
