# This is a basic workflow to help you get started with Actions

name: DynamicsJobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [pip-selftest]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-env.outputs.matrix }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      - name: read env file step
        id: file
        uses: ./actions/setEnvVariable
        with:
          #env-file-path: './.env'
          varFilePath: './.env'
      # Use the output from the `hello` step
      - name: Get the output time
        id: set-env
        run: |
          echo "$APPNAME"
          matrixStringifiedObject="{\"include\":[{\"app\":\"$APPNAME\"},{\"app\":\"$APPNAME2\"}]}"
          echo $matrixStringifiedObject
          #echo "::set-output name=matrix::$matrixStringifiedObject"
          echo "matrix=$matrixStringifiedObject" >> $GITHUB_OUTPUT
          
  #dynamics_job:
    #needs: read_env_file
    #runs-on: ubuntu-latest
    #strategy:
      #matrix: ${{ fromJson(needs.read_env_file.outputs.matrix) }}
    #steps:
    #- run: echo Run ${{ matrix.app }}
    #- run: date
    #- run: sleep 1
    #- run: date
        
  test-trigger:
    needs: read_env_file
    uses: eSandrone/testCustomActions/.github/workflows/jobCalledWithMatrix.yml@main
    with:
      ID_RUN: ${{ github.run_id }}
      IMAGE: ${{ needs.read_env_file.outputs.matrix }}
      
  # This workflow contains a single job called "example_matrix"
  read-output:
    needs: test-trigger
    runs-on: ubuntu-latest
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      - run: echo ${{ needs.test-trigger.outputs.urls2 }} 
