# This is a basic workflow to help you get started with Actions

name: DynamicsJobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    name:
      type: choice
      description: HELLO THERE
      options:
      - name-1
      - name-2
  repository_dispatch:
    types: [pip-selftest]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-env.outputs.matrix }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      - name: choice
        run: |
          echo ${{ github.event.inputs.choice }}
      - name: read env file step
        id: file
        uses: ./actions/setEnvVariable
        with:
          #env-file-path: './.env'
          varFilePath: './.env'
      # Use the output from the `hello` step
      - name: Get the output time
        id: set-env
        run: |
          echo "$APPNAME"
          matrixStringifiedObject='{"include":[{"app":"$APPNAME"},{"app":"$APPNAME2"}]}'
          echo $matrixStringifiedObject
          dummyReportText='[{"line": 1,"elements": [{"start_timestamp": "2022-10-27T10:56:14.841Z","line": 349,"name": "dummy-name","description": "","id": "dummy-id","type": "scenario","keyword": "Scenario","steps": [{"result": { "duration": 248000, "status": "passed" },"line": 350,"name": "dummy name","match": {"arguments": [{ "val": "/dummy/v1", "offset": 24 }],"location": "dummy.location"},"keyword": "Given "}]}],"name": "Endpoint /tree in PicturePanelSearch API","description": "","id": "endpoint-/tree-in-picturepanelsearch-api","keyword": "Feature","uri": "file:src/test/resources/features/tree.feature","tags": []}]'
          touch dummy-report.json
          echo "$dummyReportText" > dummy-report.json
          path=`realpath dummy-report.json`
          #echo "::set-output name=matrix::$matrixStringifiedObject"
          echo "matrix=$matrixStringifiedObject" >> $GITHUB_OUTPUT
          echo "path=$path" >> $GITHUB_OUTPUT
      - name: Get the output time
        uses: actions/upload-artifact@v2
        with:
          name: dummy-report.json
          path: ${{ steps.set-env.outputs.path }}
          
  #dynamics_job:
    #needs: read_env_file
    #runs-on: ubuntu-latest
    #strategy:
      #matrix: ${{ fromJson(needs.read_env_file.outputs.matrix) }}
    #steps:
    #- run: echo Run ${{ matrix.app }}
    #- run: date
    #- run: sleep 1
    #- run: date
        
  #test-trigger:
   # needs: read_env_file
   # uses: eSandrone/testCustomActions/.github/workflows/jobCalledWithMatrix.yml@main
   # with:
   #   ID_RUN: ${{ github.run_id }}
   #   IMAGE: ${{ needs.read_env_file.outputs.matrix }}
      
  # This workflow contains a single job called "example_matrix"
  #read-output:
  #  needs: test-trigger
  #  runs-on: ubuntu-latest
  #  steps:
     # Checks-out my repository
  #    - uses: actions/checkout@v3
  #    - run: echo ${{ needs.test-trigger.outputs.urls2 }} 
