# This is a basic workflow to help you get started with Actions

name: DynamicsJobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      - name: read env file step
        id: file
        uses: ./actions/readEnvFiles
        with:
          env-file-path: './.env'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "$APPNAME"
  dynamics_job:
    strategy:
      matrix: 
        repo: [eSandrone/todo_docker, eSandrone/actions, eSandrone/hello-world]
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          #repository: Service-and-Repairs/ckf-aws-cluster-state
         # token:  token-needed
          repository: ${{ matrix.repo }}
          token: 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
          
      - name: Check out my other private repo
        run: |
          echo Ciao
