# This is a basic workflow to help you get started with Actions

name: DynamicsJobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "example_matrix"
  read_env_file:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-env.outputs.matrix }}
      urls: ${{ steps.set-env.outputs.matrix }}
    steps:
     # Checks-out my repository
      - uses: actions/checkout@v3
      - name: read env file step
        id: file
        uses: ./actions/readEnvFiles
        with:
          env-file-path: './.env'
      # Use the output from the `hello` step
      - name: Get the output time
        id: set-env
        run: |
          echo "$APPNAME"
          matrixStringifiedObject="{\"include\":[{\"app\":\"kobra\"},{\"app\":\"zulu\"}]}"
          echo "::set-output name=image::$matrixStringifiedObject"
          matrixStringifiedObject="{\"include\":[{\"app\":\"$APPNAME\"},{\"app\":\"$APPNAME2\"}]}"
          echo "::set-output name=urls::$matrixStringifiedObject"
          
  dynamics_job:
    needs: read_env_file
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.read_env_file.outputs.image) }}
    steps:
    - run: echo Run ${{ matrix.app }}
    - run: date
    - run: sleep 1
    - run: date
        
  test-trigger:
    needs: read_env_file
    if: needs.read_env_file.outputs.update.lenght > 0
    uses: eSandrone/testCustomActions/.github/workflows/jobCalledWithMatrix.yml@main
    with:
      ID_RUN: ${{ github.run_id }}
      IMAGE: ${{ needs.read_env_file.outputs.image }}
